[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "meos"
path = "src/main.rs"
test = false
doctest = false
bench = false

[dependencies]
allocator.workspace = true
dtb_reader.workspace = true
log.workspace = true

spin.workspace = true
riscv.workspace = true
